# Generated by Django 5.0.1 on 2025-10-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("dice_score", models.FloatField(blank=True, null=True)),
                ("iou_score", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analysis",
                "verbose_name_plural": "Analyses",
                "db_table": "analysis_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
