# Generated by Django 5.0.1 on 2025-10-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="images.medicalimage",
            ),
        ),
    ]
