name: Backend Tests

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: medscan
          POSTGRES_PASSWORD: medscan_test_pass
          POSTGRES_DB: medscan_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql://medscan:medscan_test_pass@localhost:5432/medscan_test
        SECRET_KEY: test-secret-key-for-ci-only
        DEBUG: 'False'
        ALLOWED_HOSTS: localhost,127.0.0.1
      run: |
        python manage.py migrate

    - name: Run tests with coverage
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql://medscan:medscan_test_pass@localhost:5432/medscan_test
        SECRET_KEY: test-secret-key-for-ci-only
        DEBUG: 'False'
        ALLOWED_HOSTS: localhost,127.0.0.1
      run: |
        pytest --cov=apps --cov-report=xml --cov-report=term-missing --verbose

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage

    - name: Check coverage threshold
      working-directory: ./backend
      run: |
        coverage report --fail-under=80
