name: CI Pipeline

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  status:
    name: CI Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CI Status
        run: |
          echo "CI Pipeline triggered successfully"
          echo "Individual workflows (backend-ci, frontend-ci, code-quality) will run separately"
          echo "This workflow serves as an entry point for branch protection rules"
