name: Frontend Tests

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run linter
      working-directory: ./frontend
      run: npm run lint --if-present || echo "No lint script found"

    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false || echo "No tests found yet"
      env:
        CI: true

    - name: Build application
      working-directory: ./frontend
      run: npm run build
      env:
        CI: false
        REACT_APP_API_URL: http://localhost:8000/api

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build-${{ matrix.node-version }}
        path: frontend/build/
        retention-days: 7
